### ISSUE TITLE
Post-laborkowe TODO

### ISSUE THREAD

**Issue by kubasikora** [PW-EITI-ANRO-18L/anro18l-winnicki-sikora#1]
- obsługa klawiatury w skrypcie operator.py
- pobór parametrów w skrypcie set_params.py

**Comment by kubasikora** [comment]
pobór parametrów uważam za zakończony

**Comment by kubasikora** [comment]
udało się skutecznie zaimplementować obsługę klawiatury w operator.py 
dodatkowo plik launch uruchamia nowy terminal
tak więc pozostało dokończyć wiki i oddać do oceny

**Comment by stratixx** [comment]
Lodzio miodzio Panowie
