### ISSUE TITLE
Lab 3 - rviz 

### ISSUE THREAD

**Issue by stratixx** [PW-EITI-ANRO-18L/anro18l-winnicki-sikora#3]
Do zrobienia w rviz:
- wyswietlanie obliczonej pozycji

**Comment by kubasikora** [comment]
Uprasza się o zamykanie zadań po ich faktycznym zakończeniu

**Comment by stratixx** [comment]
Dziękuję za Pana opinię, każda opinia na temat działalności jest bardzo ważna. Pozdrawiam Stratixx.
