### ISSUE TITLE
Lab4 - pomysł

### ISSUE THREAD

**Issue by kubasikora** [PW-EITI-ANRO-18L/anro18l-winnicki-sikora#7]
Mam pomysł. Proponuje zrobić gui z suwakami do wysyłania tych żądań przesuwania. Może jak dr Winiarski zobaczy taki sztos to podniesie wejściówkę xd

**Comment by kubasikora** [comment]
Szczególnie że mamy miesiąc na zrobienie tego

**Comment by twiniars** [comment]
Może wejściówki nie podniesie, ale pewnie mu się to spodoba ;)

**Comment by stratixx** [comment]
Krótko i na temat: GUI działa. 
Temat zamykam.
Pzdr. K.W.
